#!/usr/bin/env python3
"""
Script 37 — TE-derived b fit test

Question:
    If Accumulation Theory predicts different observable distances depending on
    the measurement ledger, can b be derived as the mismatch between a path-only
    accumulation distance and a TE path+traversal distance?

Core idea:
    A catalog distance is not assumed to be the pure accumulation distance.
    It is a mapped observable.

    b is then:
        b_path_required - b_TE_required
      = mean(mu_TE_model - mu_path_model)

    That means the "explained b" is not fitted as an offset. It is generated by
    the TE ledger's change to the predicted distance.

Models:
    M1 path-only:
        D1 = D_geo + λ_path D_excess

    M3 TE path+traversal:
        D3 = D_geo + λ_path D_excess + λ_traverse D_geo A_local

    M3 constrained TE ratio:
        λ_path = -s
        λ_traverse = k*s
        where k is tested at:
            k=0.70, 2/3, 1/sqrt(2), 0.75

Interpretation:
    If M3-derived b explains most of M1's required b, then b is becoming
    a derived ledger-mismatch quantity rather than an arbitrary fit.
"""

from pathlib import Path
import argparse, json, math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    from scipy.optimize import differential_evolution, minimize, minimize_scalar
    SCIPY_OK=True
except Exception:
    SCIPY_OK=False

H=0.000243635
L_MPC=1/H

def D_geo(z): return L_MPC*z*(1+0.15*z)
def D_excess(z): return 0.35*L_MPC*z*z
def A_local(z): return 0.70*z/(1+0.30*z)
def mu(D):
    D=np.maximum(np.asarray(D,float),1e-12)
    return 5*np.log10(D)+25

def find_col(cols,names):
    for t in names:
        for c in cols:
            if c.lower()==t.lower(): return c
    for t in names:
        for c in cols:
            if t.lower() in c.lower(): return c
    return None

def infer(path):
    n=Path(path).stem.lower()
    if "union" in n: return "Union3"
    if "des" in n: return "DES"
    if "pantheon" in n: return "Pantheon"
    return Path(path).stem

def load(path):
    path=Path(path); df=pd.read_csv(path); cols=list(df.columns)
    zcol=find_col(cols,["z","zHD","zCMB","zcmb","redshift"])
    mucol=find_col(cols,["MU","MU_SH0ES","mu","mb","distance_modulus","distmod"])
    if zcol is None or mucol is None: return None
    out=pd.DataFrame({"catalog":infer(path),"z":pd.to_numeric(df[zcol],errors="coerce"),"mu_obs":pd.to_numeric(df[mucol],errors="coerce"),"source_file":path.name})
    out=out.replace([np.inf,-np.inf],np.nan).dropna(subset=["z","mu_obs"])
    return out[out["z"]>0].copy()

def D_model(z, model, params):
    D=D_geo(z)
    if model in ["M1","M3"]:
        D += params.get("lambda_path",0)*D_excess(z)
    if model=="M3":
        D += params.get("lambda_traverse",0)*D_geo(z)*A_local(z)
    return D

def required_b(y, mu_model):
    return float(np.mean(y-mu_model))

def fit_M1(df, include_b=True):
    z=df["z"].values; y=df["mu_obs"].values
    def eval_lam(lam):
        D=D_model(z,"M1",{"lambda_path":lam})
        if np.any(D<=0): return 1e50,0,None
        m=mu(D); b=required_b(y,m) if include_b else 0.0
        pred=m+b; return float(np.sum((y-pred)**2)),b,pred
    if SCIPY_OK:
        opt=minimize_scalar(lambda x: eval_lam(x)[0], bounds=(-12,12), method="bounded")
        lam=float(opt.x)
    else:
        grid=np.linspace(-12,12,2001); lam=float(grid[np.argmin([eval_lam(x)[0] for x in grid])])
    sse,b,pred=eval_lam(lam)
    return {"lambda_path":lam,"b_mu":b,"rmse":float(np.sqrt(np.mean((y-pred)**2))),"sse":sse}

def fit_M3_free(df, include_b=True):
    z=df["z"].values; y=df["mu_obs"].values
    def eval_x(x):
        lp,lt=float(x[0]),float(x[1])
        D=D_model(z,"M3",{"lambda_path":lp,"lambda_traverse":lt})
        if np.any(D<=0): return 1e50,0,None
        m=mu(D); b=required_b(y,m) if include_b else 0.0
        pred=m+b; return float(np.sum((y-pred)**2)),b,pred
    if SCIPY_OK:
        bnds=[(-12,12),(-12,12)]
        de=differential_evolution(lambda x: eval_x(x)[0],bnds,seed=37,maxiter=100,tol=1e-7,polish=False)
        loc=minimize(lambda x: eval_x(x)[0],de.x,method="Nelder-Mead",options={"maxiter":1000})
        x=loc.x if loc.fun<=de.fun else de.x
    else:
        grid=np.linspace(-12,12,101); best=(1e99,None)
        for lp in grid:
            for lt in grid:
                s,_,_=eval_x([lp,lt])
                if s<best[0]: best=(s,[lp,lt])
        x=np.array(best[1])
    sse,b,pred=eval_x(x)
    return {"lambda_path":float(x[0]),"lambda_traverse":float(x[1]),"b_mu":b,"rmse":float(np.sqrt(np.mean((y-pred)**2))),"sse":sse}

def fit_M3_ratio(df,k=0.70,include_b=True):
    z=df["z"].values; y=df["mu_obs"].values
    # λ_path=-s, λ_traverse=k*s
    def eval_s(s):
        params={"lambda_path":-s,"lambda_traverse":k*s}
        D=D_model(z,"M3",params)
        if np.any(D<=0): return 1e50,0,None
        m=mu(D); b=required_b(y,m) if include_b else 0.0
        pred=m+b; return float(np.sum((y-pred)**2)),b,pred
    if SCIPY_OK:
        opt=minimize_scalar(lambda s: eval_s(s)[0], bounds=(-12,12), method="bounded")
        s=float(opt.x)
    else:
        grid=np.linspace(-12,12,2001); s=float(grid[np.argmin([eval_s(x)[0] for x in grid])])
    sse,b,pred=eval_s(s)
    return {"s":s,"lambda_path":-s,"lambda_traverse":k*s,"ratio_k":k,"b_mu":b,"rmse":float(np.sqrt(np.mean((y-pred)**2))),"sse":sse}

def decompose(df, fit1, fit3, label):
    z=df["z"].values; y=df["mu_obs"].values
    mu1=mu(D_model(z,"M1",fit1))
    mu3=mu(D_model(z,"M3",fit3))
    b1=required_b(y,mu1)
    b3=required_b(y,mu3)
    b_expl=b1-b3
    pred1=mu1+b1; pred3=mu3+b3
    return {
        "variant":label,
        "b_path_required":b1,
        "b_TE_remaining":b3,
        "b_derived_from_TE":b_expl,
        "fraction_abs_b_explained":(abs(b1)-abs(b3))/abs(b1) if abs(b1)>1e-12 else np.nan,
        "rmse_path_with_b":float(np.sqrt(np.mean((y-pred1)**2))),
        "rmse_TE_with_b":float(np.sqrt(np.mean((y-pred3)**2))),
        "rmse_improvement":float(np.sqrt(np.mean((y-pred1)**2))-np.sqrt(np.mean((y-pred3)**2))),
        "mean_mu_TE_minus_path":float(np.mean(mu3-mu1))
    }

def predict_with_fit(df, model, fit):
    return mu(D_model(df["z"].values,model,fit))

def run(inputs,outdir,zmin=0.05):
    outdir=Path(outdir); outdir.mkdir(parents=True,exist_ok=True)
    dfs=[load(p) for p in inputs]; dfs=[d for d in dfs if d is not None]
    all_df=pd.concat(dfs,ignore_index=True)
    all_df=all_df[all_df["z"]>=zmin].copy()
    all_df.to_csv(outdir/"script37_loaded_catalog_points.csv",index=False)
    datasets={c:all_df[all_df["catalog"]==c].copy() for c in sorted(all_df["catalog"].unique())}
    if "Pantheon" in datasets and "Union3" in datasets:
        datasets["Pantheon_plus_Union3"]=pd.concat([datasets["Pantheon"],datasets["Union3"]],ignore_index=True)
    if "DES" in datasets and "Pantheon" in datasets:
        zlo=max(datasets["DES"]["z"].min(),datasets["Pantheon"]["z"].min(),zmin)
        zhi=min(datasets["DES"]["z"].max(),datasets["Pantheon"]["z"].max())
        datasets["DES_plus_Pantheon_common"]=pd.concat([
            datasets["DES"][(datasets["DES"]["z"]>=zlo)&(datasets["DES"]["z"]<=zhi)],
            datasets["Pantheon"][(datasets["Pantheon"]["z"]>=zlo)&(datasets["Pantheon"]["z"]<=zhi)]
        ],ignore_index=True)
    datasets["All_three"]=all_df.copy()

    rows=[]; coeff_rows=[]
    ks=[0.70,2/3,1/math.sqrt(2),0.75]
    fits_by_dataset={}
    for name,df in datasets.items():
        if len(df)<8: continue
        f1=fit_M1(df,True)
        f3=fit_M3_free(df,True)
        fits_by_dataset[(name,"M1")]=f1; fits_by_dataset[(name,"M3_free")]=f3
        rec=decompose(df,f1,f3,"M3_free")
        rows.append({"dataset":name,**rec,**{"lambda_path":f3["lambda_path"],"lambda_traverse":f3["lambda_traverse"],"ratio":f3["lambda_traverse"]/abs(f3["lambda_path"]) if f3["lambda_path"] else np.nan}})
        coeff_rows.append({"dataset":name,"variant":"M1_path",**f1})
        coeff_rows.append({"dataset":name,"variant":"M3_free",**f3})
        for k in ks:
            fr=fit_M3_ratio(df,k,True)
            rec=decompose(df,f1,fr,f"M3_ratio_k_{k:.6f}")
            rows.append({"dataset":name,**rec,**{"lambda_path":fr["lambda_path"],"lambda_traverse":fr["lambda_traverse"],"ratio":k}})
            coeff_rows.append({"dataset":name,"variant":f"M3_ratio_k_{k:.6f}",**fr})

    decomp=pd.DataFrame(rows); decomp.to_csv(outdir/"script37_TE_derived_b_decomposition.csv",index=False)
    coefs=pd.DataFrame(coeff_rows); coefs.to_csv(outdir/"script37_fit_coefficients.csv",index=False)

    # Cross-family derived b using P+U coefficients.
    cross_rows=[]
    if ("Pantheon_plus_Union3","M3_free") in fits_by_dataset and ("Pantheon_plus_Union3","M1") in fits_by_dataset:
        f1_fam=fits_by_dataset[("Pantheon_plus_Union3","M1")]
        f3_fam=fits_by_dataset[("Pantheon_plus_Union3","M3_free")]
        for name,df in datasets.items():
            if len(df)<8: continue
            rec=decompose(df,f1_fam,f3_fam,"P+U_coefficients_applied")
            cross_rows.append({"target_dataset":name,**rec,**{"lambda_path":f3_fam["lambda_path"],"lambda_traverse":f3_fam["lambda_traverse"]}})
        # also ratio k=.70 fitted on P+U
        fr_fam=fit_M3_ratio(datasets["Pantheon_plus_Union3"],0.70,True)
        for name,df in datasets.items():
            if len(df)<8: continue
            rec=decompose(df,f1_fam,fr_fam,"P+U_ratio_k_0.70_applied")
            cross_rows.append({"target_dataset":name,**rec,**{"lambda_path":fr_fam["lambda_path"],"lambda_traverse":fr_fam["lambda_traverse"]}})
    cross=pd.DataFrame(cross_rows); cross.to_csv(outdir/"script37_cross_applied_TE_derived_b.csv",index=False)

    # Plots
    plot=decomp[decomp["variant"].isin(["M3_free","M3_ratio_k_0.700000"])].copy()
    if len(plot):
        labels=plot["dataset"]+" | "+plot["variant"]
        plt.figure(figsize=(max(12,len(plot)*0.45),5))
        x=np.arange(len(plot))
        plt.bar(x,plot["fraction_abs_b_explained"])
        plt.axhline(0.75,ls="--",label="75%")
        plt.axhline(0, lw=1)
        plt.xticks(x,labels,rotation=75,ha="right",fontsize=8)
        plt.ylabel("fraction of path-only b explained")
        plt.title("Script 37: TE-derived b explanation")
        plt.legend(); plt.tight_layout()
        plt.savefig(outdir/"script37_fraction_b_explained.png",dpi=180); plt.close()

    if len(cross):
        labels=cross["target_dataset"]+" | "+cross["variant"]
        plt.figure(figsize=(max(12,len(cross)*0.5),5))
        x=np.arange(len(cross))
        plt.bar(x,cross["fraction_abs_b_explained"])
        plt.axhline(0.75,ls="--",label="75%")
        plt.axhline(0,lw=1)
        plt.xticks(x,labels,rotation=75,ha="right",fontsize=8)
        plt.ylabel("fraction of b explained")
        plt.title("Script 37: family TE ledger applied across catalogs")
        plt.legend(); plt.tight_layout()
        plt.savefig(outdir/"script37_cross_applied_b_explained.png",dpi=180); plt.close()

    # Family summary
    fam=decomp[(decomp["dataset"].isin(["Pantheon","Union3","Pantheon_plus_Union3"])) & (decomp["variant"]=="M3_ratio_k_0.700000")]
    fam_free=decomp[(decomp["dataset"].isin(["Pantheon","Union3","Pantheon_plus_Union3"])) & (decomp["variant"]=="M3_free")]
    verdict={
        "script":"37_TE_derived_b_fit_test.py",
        "purpose":"Test whether b can be derived as the mismatch between path-only accumulation distance and TE path+traversal observable distance.",
        "key_identity":"b_derived_from_TE = mean(mu_TE_model - mu_path_model) = b_path_required - b_TE_remaining",
        "ratio_model":"λ_path=-s, λ_traverse=k*s; k=0.70 tests the A_local/path derivative clue.",
        "family_M3_free_mean_fraction_explained":float(fam_free["fraction_abs_b_explained"].mean()) if len(fam_free) else None,
        "family_k_0p70_mean_fraction_explained":float(fam["fraction_abs_b_explained"].mean()) if len(fam) else None,
        "interpretation":[
            "If b_derived_from_TE removes most path-only b, b is a ledger mismatch rather than arbitrary offset.",
            "If k=0.70 works close to free M3, the derivation can be constrained by A_local/path structure.",
            "Remaining b is catalog/mapping residue."
        ]
    }
    (outdir/"script37_verdict.json").write_text(json.dumps(verdict,indent=2))
    print("Script 37 TE-derived b fit test complete.")
    print(f"Output directory: {outdir}")
    print("\nTE-derived b decomposition:")
    print(decomp[["dataset","variant","b_path_required","b_TE_remaining","b_derived_from_TE","fraction_abs_b_explained","rmse_improvement","lambda_path","lambda_traverse","ratio"]].to_string(index=False))
    print("\nCross-applied TE-derived b:")
    print(cross[["target_dataset","variant","b_path_required","b_TE_remaining","b_derived_from_TE","fraction_abs_b_explained","rmse_improvement","lambda_path","lambda_traverse"]].to_string(index=False) if len(cross) else "No cross rows.")
    print("\nVerdict:")
    print(json.dumps(verdict,indent=2))
if __name__=="__main__":
    p=argparse.ArgumentParser(); p.add_argument("--inputs",nargs="+",required=True); p.add_argument("--outdir",default="results/script37_TE_derived_b"); p.add_argument("--zmin",type=float,default=0.05)
    a=p.parse_args(); run(a.inputs,a.outdir,zmin=a.zmin)
